default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agile_board_development


test:
  <<: *default
  database: agile_board_test

production:
  <<: *default
  database: agile_board_production
  username: agile_board
  password: <%= ENV['AGILE-BOARD_DATABASE_PASSWORD'] %>
